// Generated by CoffeeScript 1.6.3
myApp.factory('championService', function() {
  return {
    champions: [
      {
        name: 'Annie',
        rp_cost: 260,
        ip_cost: 450,
        lane: 'Middle Lane',
        released: '2/21/2009',
        thumb_url: 'public/images/champions/1_32.png'
      }, {
        name: 'Olaf',
        rp_cost: 790,
        ip_cost: 3150,
        lane: 'Top Lane',
        released: '6/9/2010',
        thumb_url: 'public/images/champions/2_32.png'
      }, {
        name: 'Galio',
        rp_cost: 880,
        ip_cost: 4800,
        lane: 'Middle Lane',
        released: '8/10/2010',
        thumb_url: 'public/images/champions/3_32.png'
      }, {
        name: 'Twisted Fate',
        rp_cost: 585,
        ip_cost: 1350,
        lane: 'Middle Lane',
        released: '2/21/2009',
        thumb_url: 'public/images/champions/4_32.png'
      }, {
        name: 'Xin Zhao',
        rp_cost: 790,
        ip_cost: 3150,
        lane: 'Jungler',
        released: '7/13/2010',
        thumb_url: 'public/images/champions/5_32.png'
      }, {
        name: 'Urgot',
        rp_cost: 790,
        ip_cost: 3150,
        lane: 'AD Carry',
        released: '8/24/2010',
        thumb_url: 'public/images/champions/6_32.png'
      }, {
        name: 'LeBlanc',
        rp_cost: 790,
        ip_cost: 3150,
        lane: 'Middle Lane',
        released: '11/2/2010',
        thumb_url: 'public/images/champions/7_32.png'
      }, {
        name: 'Vladimir',
        rp_cost: 880,
        ip_cost: 4800,
        lane: 'Middle Lane',
        released: '7/27/2010',
        thumb_url: 'public/images/champions/8_32.png'
      }, {
        name: 'Fiddlesticks',
        rp_cost: 585,
        ip_cost: 1350,
        lane: 'Jungler',
        released: '2/21/2009',
        thumb_url: 'public/images/champions/9_32.png'
      }, {
        name: 'Kayle',
        rp_cost: 260,
        ip_cost: 450,
        lane: 'Middle Lane',
        released: '2/21/2009',
        thumb_url: 'public/images/champions/10_32.png'
      }, {
        name: 'Master Yi',
        rp_cost: 260,
        ip_cost: 450,
        lane: 'Middle Lane',
        released: '2/21/2009',
        thumb_url: 'public/images/champions/11_32.png'
      }, {
        name: 'Alistar',
        rp_cost: 585,
        ip_cost: 1350,
        lane: 'Support',
        released: '2/21/2009',
        thumb_url: 'public/images/champions/12_32.png'
      }, {
        name: 'Ryze',
        rp_cost: 260,
        ip_cost: 450,
        lane: 'Middle Lane',
        released: '2/21/2009',
        thumb_url: 'public/images/champions/13_32.png'
      }, {
        name: 'Sion',
        rp_cost: 585,
        ip_cost: 1350,
        lane: 'Middle Lane',
        released: '2/21/2009',
        thumb_url: 'public/images/champions/14_32.png'
      }, {
        name: 'Sivir',
        rp_cost: 260,
        ip_cost: 450,
        lane: 'AD Carry',
        released: '2/21/2009',
        thumb_url: 'public/images/champions/15_32.png'
      }
    ]
  };
});
