// Generated by CoffeeScript 1.6.3
myApp.controller('ErrorCtrl', function($scope) {
  return $scope.back = function() {
    window.history.back();
    return console.log(window.history.back());
  };
});
