// Generated by CoffeeScript 1.6.3
myApp.controller('GalleryCtrl', function($scope, $dialog) {
  $scope.images = [
    {
      id: 1,
      url: 'public/images/eve.jpg',
      name: 'Evelynn'
    }, {
      id: 2,
      url: 'public/images/jax.jpg',
      name: 'Jax'
    }, {
      id: 3,
      url: 'public/images/kat.jpg',
      name: 'Katarina'
    }, {
      id: 4,
      url: 'public/images/xin.jpg',
      name: 'Xin Zhao'
    }, {
      id: 5,
      url: 'public/images/yi.jpg',
      name: 'Master Yi'
    }
  ];
  return $scope.showImage = function(image) {
    var d, opts, resolvedData;
    $scope.opts = {
      backdrop: true,
      keyboard: true,
      dialogFade: true,
      backdropClick: true,
      templateUrl: 'app/templates/gallery_image.html',
      controller: 'GalleryImageCtrl'
    };
    resolvedData = {
      resolve: {
        image: function() {
          return image;
        }
      }
    };
    opts = angular.extend($scope.opts, resolvedData);
    d = $dialog.dialog(opts);
    return d.open();
  };
}).controller('GalleryImageCtrl', function($scope, dialog, image) {
  return $scope.image = image;
});
