// Generated by CoffeeScript 1.6.3
myApp.controller('HomeCtrl', function($scope) {
  var clearInput;
  $scope.list = [
    {
      name: 'lol',
      age: 19
    }, {
      name: 'John',
      age: 22
    }
  ];
  clearInput = function() {
    $scope.name = '';
    return $scope.age = '';
  };
  $scope.addEntry = function() {
    $scope.list.push({
      name: $scope.name,
      age: $scope.age
    });
    return clearInput();
  };
  return $scope.deleteEntry = function(entry) {
    return $scope.list.splice($scope.list.indexOf(entry), 1);
  };
});
