// Generated by CoffeeScript 1.6.3
myApp.controller('NavCtrl', [
  '$scope', '$location', function($scope, $location) {
    $scope.items = [
      {
        url: '#/',
        name: 'Home',
        path: '/',
        "class": ''
      }, {
        url: '#/entries',
        name: 'Entries',
        path: 'entries',
        "class": ''
      }, {
        url: '#/gallery',
        name: 'Gallery',
        path: 'gallery',
        "class": ''
      }, {
        url: '#/about',
        name: 'About',
        path: 'about',
        "class": ''
      }
    ];
    $scope.setActive = function() {
      var currentRoute;
      currentRoute = $location.path().substring(1) || '/';
      return $($scope.items).each(function(i, v) {
        return v["class"] = v.path === currentRoute ? 'active' : '';
      });
    };
    return $scope.$on("$routeChangeSuccess", function($currentRoute, $previousRoute) {
      return $scope.setActive();
    });
  }
]);
