// Generated by CoffeeScript 1.6.3
myApp.directive("ngDraggable", function() {
  return function(scope, element, attr) {
    var drop, move;
    move = function(event) {
      element[0].style.top = event.y - 15 + "px";
      return element[0].style.left = event.x - 20 + "px";
    };
    drop = function(event) {
      document.removeEventListener('mousemove', move);
      document.removeEventListener('mouseup', drop);
      element[0].style.position = "relative";
      element[0].style.zIndex = 1;
      $('table tbody').append(element[0]);
      return $('body').removeClass('no-select');
    };
    return element.bind('mousedown', function() {
      element[0].style.zIndex = 200;
      element[0].style.position = "absolute";
      $('body').addClass('no-select');
      element[0].remove();
      $('body').append(element[0]);
      document.addEventListener('mousemove', move);
      return document.addEventListener('mouseup', drop);
    });
  };
});
